#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pyperclip
Version  : 1.7.0
Release  : 5
URL      : https://files.pythonhosted.org/packages/2d/0f/4eda562dffd085945d57c2d9a5da745cfb5228c02bc90f2c74bbac746243/pyperclip-1.7.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/2d/0f/4eda562dffd085945d57c2d9a5da745cfb5228c02bc90f2c74bbac746243/pyperclip-1.7.0.tar.gz
Summary  : A cross-platform clipboard module for Python. (Only handles plain text for now.)
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pyperclip-python3
Requires: pyperclip-python
BuildRequires : buildreq-distutils3

%description
`pip install pyperclip`
        
        Al Sweigart al@inventwithpython.com
        BSD License
        
        Example Usage
        =============
        
            >>> import pyperclip
            >>> pyperclip.copy('The text to be copied to the clipboard.')
            >>> pyperclip.paste()
            'The text to be copied to the clipboard.'
        
        
        Currently only handles plaintext.
        
        On Windows, no additional modules are needed.
        
        On Mac, this module makes use of the pbcopy and pbpaste commands, which should come with the os.

%package python
Summary: python components for the pyperclip package.
Group: Default
Requires: pyperclip-python3 = %{version}-%{release}

%description python
python components for the pyperclip package.


%package python3
Summary: python3 components for the pyperclip package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pyperclip package.


%prep
%setup -q -n pyperclip-1.7.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1537844253
python3 setup.py build

%install
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
