#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pyperclip
Version  : 1.8.0
Release  : 12
URL      : https://files.pythonhosted.org/packages/f6/5b/55866e1cde0f86f5eec59dab5de8a66628cb0d53da74b8dbc15ad8dabda3/pyperclip-1.8.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/f6/5b/55866e1cde0f86f5eec59dab5de8a66628cb0d53da74b8dbc15ad8dabda3/pyperclip-1.8.0.tar.gz
Summary  : A cross-platform clipboard module for Python. (Only handles plain text for now.)
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pyperclip-python = %{version}-%{release}
Requires: pyperclip-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
Pyperclip is a cross-platform Python module for copy and paste clipboard functions. It works with Python 2 and 3.

%package python
Summary: python components for the pyperclip package.
Group: Default
Requires: pyperclip-python3 = %{version}-%{release}

%description python
python components for the pyperclip package.


%package python3
Summary: python3 components for the pyperclip package.
Group: Default
Requires: python3-core
Provides: pypi(pyperclip)

%description python3
python3 components for the pyperclip package.


%prep
%setup -q -n pyperclip-1.8.0
cd %{_builddir}/pyperclip-1.8.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1585690810
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
